services:
  postgres:
    image: postgres:15
    container_name: sispce_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170414
      POSTGRES_DB: sispce
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  sispce_backend:
    build: ../sispce-BACKEND/sispce
    container_name: sispce_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sispce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 170414
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  sispce_frontend:
    build: .
    container_name: sispce_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - sispce_backend

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecreto
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=sispce
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=170414
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
