export enum StatusNce {
  CRIADA = 'CRIADA',
  EM_ANALISE_CMT = 'EM_ANALISE_CMT',
  DEFERIDO_CMT = 'DEFERIDO_CMT',
  INDEFERIDO_CMT = 'INDEFERIDO_CMT',
  EM_ANALISE_CADESM = 'EM_ANALISE_CADESM',
  DEFERIDO_CADESM = 'DEFERIDO_CADESM',
  INDEFERIDO_CADESM = 'INDEFERIDO_CADESM',
  EM_ANALISE_DIRETORIA = 'EM_ANALISE_DIRETORIA',
  DEFERIDO_DIRETORIA = 'DEFERIDO_DIRETORIA',
  INDEFERIDO_DIRETORIA = 'INDEFERIDO_DIRETORIA',
  EM_ANALISE_EME = 'EM_ANALISE_EME',
  APROVADO_EME = 'APROVADO_EME',
  REPROVADO_EME = 'REPROVADO_EME',
  LIBERADO_CANDIDATO = 'LIBERADO_CANDIDATO',
  DELETADO = 'DELETADO'
}

